src/base/urls.py
import os

from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, reverse

urlpatterns = [
    path("admin/", admin.site.urls),
    path("about/", include(("about.urls", "about"), namespace="about")),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
    path("exclusive/", include(("exclusive.urls", "exclusive"), namespace="exclusive")),
    path("", lambda _: redirect(reverse("blog:index"))),
]

if os.environ.get("APP_ENV") == "development":  # pragma: no cover
    dev_urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns = urlpatterns + dev_urlpatterns

src/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<slug:slug>/", views.post, name="post"),
    path("archive/<slug:slug>/", views.archive, name="archive"),
    path("tag/<slug:slug>/", views.tag, name="tag"),
]

src/exclusive/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

src/projects/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<slug:slug>/", views.post, name="post"),
]

src/about/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from about.managers import ProfileManager


class Profile(AbstractUser):
    email = models.EmailField(unique=True)
    image_title = models.CharField(max_length=25)
    image_alt = models.CharField(max_length=50)
    image_src_url = models.TextField()

    objects = ProfileManager()

    def __str__(self):
        return self.name

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"


class Link(models.Model):
    class Meta:
        ordering = ["icon_title"]

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    icon_title = models.CharField(max_length=25)
    icon_alt = models.CharField(max_length=50)
    icon_href = models.CharField(max_length=250)
    icon_src_url = models.TextField()

    def __str__(self):
        return self.icon_title


class Timeline(models.Model):
    class Meta:
        ordering = ["-created_on"]

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    header = models.CharField(max_length=120, unique=True)
    body = models.TextField()

    def __str__(self):
        return self.header

src/blog/models.py
from django.db import models

from about.models import Profile
from blog.managers import PostManager


class Tag(models.Model):
    class Meta:
        ordering = ["name"]

    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    class Meta:
        ordering = ["-published_on"]

    author = models.ForeignKey(Profile, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255, unique=True)
    subtitle = models.CharField(max_length=255, blank=True)
    meta_description = models.CharField(max_length=150, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    published_on = models.DateTimeField(blank=True, null=True)
    published = models.BooleanField(default=False)
    abstract = models.TextField()
    body = models.TextField()

    objects = PostManager()

    def __str__(self):
        return self.title

src/exclusive/models.py
from django.db import models


# TODO: when ready to implement change class name symbol
class Exclusive(models.Model):
    pass

src/about/views.py
from django.shortcuts import render

from .models import Profile


def index(request):
    profile, links, timelines = Profile.objects.get_profile_links_timelines_for_superuser()
    return render(request, "about/index.html", locals())

src/blog/views.py
from django.shortcuts import render

from .models import Post


def index(request):
    posts = Post.objects.get_published_posts()
    tags = Post.objects.group_posts_by_tag_with_count()
    archives = Post.objects.group_posts_by_year_with_count()
    return render(request, "blog/index.html", locals())


def post(request, slug):
    (post, prev, next) = Post.objects.get_current_prev_next_posts(slug)
    tags = Post.objects.group_posts_by_tag_with_count()
    archives = Post.objects.group_posts_by_year_with_count()
    return render(request, "blog/post.html", locals())


def archive(request, slug):
    posts = Post.objects.get_archived_posts(slug)
    archives = Post.objects.group_posts_by_year_with_count()
    tags = Post.objects.group_posts_by_tag_with_count()
    return render(request, "blog/archive.html", locals())


def tag(request, slug):
    posts = Post.objects.get_tagged_posts(slug)
    archives = Post.objects.group_posts_by_year_with_count()
    tags = Post.objects.group_posts_by_tag_with_count()
    return render(request, "blog/tag.html", locals())

src/exclusive/views.py
from django.shortcuts import render


def index(request):
    context = dict()
    return render(request, "exclusive/index.html", context)

src/about/templates/about/index.html
{% extends "base/index.html" %}

{% block title %}About{% endblock %}

{% block content %}
<main style="margin-top: 5em;">
  <div id="title-banner"></div>
  <section>
      <figure>
        <img
          src="{{ profile.image_src_url }}"
          alt="{{ profile.image_alt }}"
          title="{{ profile.image_title }}"
          width="175px"
          height="175px"
          style="
            border-radius: 50%;
            margin: auto;
            display: block;
            "
        />
        <figcaption style="margin: 1.25em auto;">{{ profile.name }}</figcaption>
      </figure>
  </section>
  
  <section style="text-align: center;">
    {% for link in links %}
      <span>
        <a class="no-hover-bg" href="{{ link.icon_href }}">
          <img
            src="{{ link.icon_src_url }}"
            alt="{{ link.icon_alt }}"
            title="{{ link.icon_title }}"
            width="24px"
            height="24px"
          />
        </a>
      </span>
    {% endfor %}
  </section>
  
  <section style="margin-top: 2.5em;">
    <div class="terminal-timeline">
      {% for timeline in timelines %}
        <div class="terminal-card">
          <header style="text-align: left;">{{ timeline.header }}</header>
          <div>
            {{timeline.body}}
          </div>
        </div>
      {% endfor %}
    </div>
    <br />
  </section>
</main>
{% endblock %}

src/base/templates/base/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link type="text/css" rel="stylesheet" href="{% static 'base/css/normalize.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'base/css/jquery-ui.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'base/css/jquery-ui-1.12.icon-font.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'base/css/material-icons.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'base/css/terminal.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'base/css/theme.css' %}" />
    <script type="text/javascript" src="{% static 'base/js/vendors/jquery/jquery.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'base/js/vendors/jquery/jquery-ui.min.js' %}" defer></script>
    <script type="text/javascript" src="{% static 'base/js/dist/index.iife.js' %}" defer></script>
    <!-- TODO: implement detailed head with manifest comment out unused styles -->
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body class="terminal container container-fluid">
    {% include "base/partials/navbar.html" %}
    {% block content %}{% endblock %}
    {% include "base/partials/footer.html" %}
  </body>
</html>

src/base/templates/base/partials/footer.html
<section>
    <hr/>
    <div style="display:flex; flex-wrap: wrap;">
      <span>
        © {% now "Y" %} | 
        <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener noreferrer"> CC0 1.0 Universal</a>
      </span>
      <span style="flex: 1; padding: 1em 0;"></span>
      <span>
        <a href="https://github.com/nanacnote/diaryofapolymath" target="_blank" rel="noopener noreferrer">Codebase</a> |
        Powered by <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">django</a>
      </span>

    </div>
    <hr style="opacity: 0; margin-bottom: 0;"/>
</section>

src/base/templates/base/partials/navbar.html
<section>
    <div class="terminal-nav">
      <div class="terminal-logo">
        <div class="logo terminal-prompt"><a href="/" class="no-style">Diary of a Polymath</a></div>
      </div>
      <nav class="terminal-menu">
        <ul>
          {% with base_route_var=request.resolver_match.route %}
          <li><a class="{% if 'about/' in base_route_var %} active {% endif %}" href="{% url 'about:index' %}">About</a></li>
          <li><a class="{% if 'blog/' in base_route_var %} active {% endif %}" href="{% url 'blog:index' %}">Blog</a></li>
          <li><a class="{% if 'exclusive/' in base_route_var %} active {% endif %}" href="{% url 'exclusive:index' %}">Exclusive</a></li>
          {% endwith %}
          <li id="theme-switch" data-controller="theme-handler">
            <input id="theme-switch-input" type="checkbox" data-action="change->theme-handler#toggle" />
            <label for="theme-switch-input"></label>
          </li>
        </ul>
      </nav>
    </div>
</section>

src/blog/templates/blog/archive.html
{% extends "base/index.html" %}

{% block title %}Blog | Archive{% endblock %}

{% block content %}
<section class="components-grid show-aside" style="margin-top: 5em;">
  <main>
    <div id="title-banner">{{request.resolver_match.kwargs.slug|add:" Archive"}}</div>
    {% for post in posts %}
      <div id="{{ post.slug }}">
        <h1>{{ post.title }}</h1>
          {% include "blog/partials/post_stats.html" %}
          <p style="color: var(--secondary-color); text-align: justify;">{{ post.abstract}}</p>
          {% include "blog/partials/post_tags.html" %}
          <div>
            <a class="no-hover-bg btn btn-default btn-ghost" style="margin-top: 1em;" href="{% url 'blog:post' post.slug %}">Read More</a>
          </div>
      </div>
      {% if not forloop.last %}
        <hr/>
      {% endif %}
    {% endfor %}
  </main>
  {% include "blog/partials/aside_menu.html" %}
</section>
{% endblock %}

src/blog/templates/blog/index.html
{% extends "base/index.html" %}

{% block title %}Blog{% endblock %}

{% block content %}
<section class="components-grid show-aside" style="margin-top: 5em;">
  <main>
    <div id="title-banner">Blog</div>
    {% for post in posts %}
      <div id="{{ post.slug }}">
        <h1>{{ post.title }}</h1>
          {% include "blog/partials/post_stats.html" %}
          <p style="color: var(--secondary-color); text-align: justify;">{{ post.abstract}}</p>
          {% include "blog/partials/post_tags.html" %}
          <div>
            <a class="no-hover-bg btn btn-default btn-ghost" style="margin-top: 1em;" href="{% url 'blog:post' post.slug %}">Read More</a>
          </div>
      </div>
      {% if not forloop.last %}
        <hr/>
      {% endif %}
    {% endfor %}
  </main>
  {% include "blog/partials/aside_menu.html" %}
</section>
{% endblock %}

src/blog/templates/blog/partials/aside_menu.html
<aside>
    <div style="position: sticky; top: 25px;">
      <div>
        <h1>Pinned</h1>
        <!-- Todo: add image src -->
        <img style="border-radius: 0.25em;" width="205px" height="auto" alt="image of sponsor" src="https://picsum.photos/205/205">
      </div>
      <div>
        <h1>Tags</h1>
        <ul>
          {% for tag in tags %}
            <li>
              <a style="display: flex;" href="{% url 'blog:tag' tag.slug %}">
                <span>{{ tag.name }}</span>
                <span style="flex: 1;"></span>
                <span>[{{ tag.count }}]</span>
              </a>
            </li>
          {% endfor%}
        </ul>
      </div>
      <div>
        <h1>Archive</h1>
        <ul>
          {% for archive in archives %}
            <li>
              <a style="display: flex;" href="{% url 'blog:archive' archive.year %}">
                <span>{{ archive.year }}</span>
                <span style="flex: 1;"></span>
                <span>[{{ archive.count }}]</span>
              </a>
            </li>
          {% endfor%}
        </ul>
      </div>
    </div>
</aside>

src/blog/templates/blog/partials/post_cta.html
<div>
    <a class="btn btn-rounded-icon" href="#">
        <span class="material-symbols-rounded material-icon-like" style="font-size: 12px;"></span>
    </a>
    <a class="btn btn-rounded-icon" href="#">
        <span class="material-symbols-rounded material-icon-comment" style="font-size: 12px;"></span>
    </a>
</div>

src/blog/templates/blog/partials/post_stats.html
{% load post_utils %}

<div>
    <p style="color: var(--secondary-color);">
        <span class="material-symbols-rounded material-icon-calender-month"></span><span>&nbsp;{{ post.published_on|date:"F Y" }}</span>
        &nbsp;&nbsp;<span class="material-symbols-rounded material-icon-timmer"></span><span>&nbsp;{{ post.body|read_time }}</span>
    </p>
</div>

src/blog/templates/blog/partials/post_tags.html
<div>
    {% for tag in post.tags.all %}
        <a href="{% url 'blog:tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %} • {% endif %}
    {% endfor %}
</div>

src/blog/templates/blog/post.html
{% extends "base/index.html" %}

{% block title %}Blog | {{ post.title }}{% endblock %}

{% block content %}
<section class="components-grid show-aside" style="margin-top: 5em;">
  <div id="title-banner"></div>
  <main>
    <div>
      <h1>
        <span>{{ post.title }}</span>
        <span style="color: var(--secondary-color);"> | </span>
        <span style="color: var(--secondary-color);">{{ post.subtitle }}</span>
      </h1>

      <div style="display: flex;">
        {% include "blog/partials/post_stats.html" %}
        <span style="flex: 1;"></span>
        {% include "blog/partials/post_cta.html" %}
      </div>
      {% include "blog/partials/post_tags.html" %}

      <div style="margin-top: 1em; text-align: justify;" data-controller="content-parser">{{ post.body }}</div>
  
      <div style="display:flex; flex-wrap: wrap; margin-top: 2em;">
        <span>
          {% if prev %}
            <a class="no-hover-bg btn btn-default btn-ghost" style="text-align: center; width: 275px; flex-direction: column;" href="{% url 'blog:post' prev.slug %}">
              <strong>Previous</strong>
              <span>{{ prev.title|truncatechars:20 }}</span>
            </a>
          {% endif %}
        </span>
        <span style="flex: 1; padding: 1em 0;"></span>
        <span>
          {% if next %}
            <a class="no-hover-bg btn btn-default btn-ghost" style="text-align: center; width: 275px; flex-direction: column;" href="{% url 'blog:post' next.slug %}">
              <strong>Next</strong>
              <span>{{ next.title|truncatechars:20 }}</span>
            </a>
          {% endif %}
        </span>
      </div>
    </div>
  </main>
  {% include "blog/partials/aside_menu.html" %}
</section>
{% endblock %}

src/blog/templates/blog/tag.html
{% extends "base/index.html" %}

{% block title %}Blog | Tag{% endblock %}

{% block content %}
<section class="components-grid show-aside" style="margin-top: 5em;">
  <main>
    <div id="title-banner">{{"Tagged "|add:request.resolver_match.kwargs.slug}}</div>
    {% for post in posts %}
      <div id="{{ post.slug }}">
        <h1>{{ post.title }}</h1>
          {% include "blog/partials/post_stats.html" %}
          <p style="color: var(--secondary-color); text-align: justify;">{{ post.abstract}}</p>
          {% include "blog/partials/post_tags.html" %}
          <div>
            <a class="no-hover-bg btn btn-default btn-ghost" style="margin-top: 1em;" href="{% url 'blog:post' post.slug %}">Read More</a>
          </div>
      </div>
      {% if not forloop.last %}
        <hr/>
      {% endif %}
    {% endfor %}
  </main>
  {% include "blog/partials/aside_menu.html" %}
</section>
{% endblock %}

src/exclusive/templates/exclusive/index.html
{% extends "base/index.html" %}

{% block title %}Exclusive{% endblock %}

{% block content %}
  Coming Soon.
{% endblock %}

src/projects/templates/projects/index.html
{% extends "base/base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
  Projects
{% endblock %}